### ISSUE TITLE
Not available on Packagist

### ISSUE THREAD

**Issue by ddeboer** [php-http/adapter-client#1]
This package is not available on Packagist. Is that on purpose? The same is true for php-http/client.

**Comment by sagikazarmark** [comment]
It is not ready yet. Will be available soon.

**Comment by ddeboer** [comment]
Cool! I’d like to start using them to make https://github.com/FriendsOfSymfony/FOSHttpCache/pull/173 compatible with PHP 5.4 by replacing the hard (dev) dependency on Guzzle 6 with this package.

**Comment by sagikazarmark** [comment]
Currently I am writting some documentation. Since the basic adapters are tagged and working, this the next task on my todo list. I would say in the next few days I put it on packagist.

But  I don't understand why you want to use this. This will allow `$client->get('uri')` like calls. HttpCache uses PSR-7 requests, doesn't it? Also, this will NOT provide adapter-implementation virtual package, since this adapter needs an underlying adapter.

**Comment by ddeboer** [comment]
We use PSR-7 for the invalidation requests but we also provide a TestCase for testing app caching rules. To validate cache hits/misses, a generic HTTP client needs to be available in that test class.

**Comment by sagikazarmark** [comment]
Registered on packagist
